### ISSUE TITLE
Performance issues in AS2 servlet when transferring files

### ISSUE THREAD

**Issue by ihudedi** [phax/as2-lib#124] opened 2021-08-04 09:13 UTC
Hi @phax 
The performance when transfering files with sockets in comparison to servlet is significant.
The bit rate in servlet is very small.
Could you please let me know if it's an known issue?
Thanks,
Itay

**Comment by avnerw74** [comment] 2021-08-09 07:56
Hi @phax , are you aware of performance issue with the servlet?
We switched from AS2 server to AS2 Servlet recently in our code, and files in our test environments are now transferred extremely slow.
With AS2 Server, uploading a single file with size of 100KB took less than 1 second.
With AS2 Servlet, uploading a single file with size of 100KB takes 295 seconds!!

Any idea? Any parameters/configuration we might be missing?

Best Regards,
Avner

**Comment by phax** [comment] 2021-08-09 10:56
Hi guys,
this is a duplicate of #121 
As stated there: that depends on your environment.
The code is exactly the same, except, that all the logic of the application server (Tomcat, Jetty, Wildfly, ....) is inbetween, and there might be lots of custom JEE filters, listeners etc.
There is no generic answer to your question - sorry.

**Closed by phax** 2021-08-09 10:56 UTC
