### ISSUE TITLE
Verification failed when retrieve mdn sync

### ISSUE THREAD

**Issue by Gentle-Chen** [phax/as2-lib#102] opened 2020-01-16 02:50 UTC
Hi Philip,

When I sync retrieve the mdn from partner, it show the verification failed exception while I use sign algorithm SHA256 and encryption algorithm aes256.
![as2-error](https://user-images.githubusercontent.com/26357197/72489112-00306e80-384e-11ea-8847-5c56023065b6.png)

Could you advise the reason it may be?

Thanks for you help.

**Comment by phax** [comment] 2020-01-16 08:33
Well, my assumption is, that the receiving side does not honor the name of signing/encryption algorithms and instead just uses SHA-256 and AES256 independent of the sender?

Please try to contact the receiver and figure out there configuration settings and there requirements....
Basically they are not adhering to the AS2 specification but not honoring the requested algorithms. If they don't support an algorithm, they should instead return a negative MDN with the respective description.

**Comment by Gentle-Chen** [comment] 2020-01-16 08:38
so do you mean to the  matched sign algorithm SHA256 and encryption algorithm aes256 are not matched between our side and partner's side?

**Comment by phax** [comment] 2020-01-16 11:15
Yes that would be my suggestion without knowing the details of your nor the other system

**Comment by Gentle-Chen** [comment] 2020-01-17 07:48
Hi Philip,

It seems at partner side, they can receive the message and successfully verify it, and there is no error at their side..

Do you know why, according to your experience?

**Comment by phax** [comment] 2020-01-17 10:12
Hi @Gentle-Chen 
okay, I was try read the screenshot in more detail. According to my understanding:
1. you are not using the latest version of as2-lib (v4.5.0) - correct?
1. you are sending an AS2 message - correct?
1. In that AS2 message your are requesting a sync MDN - correct?
1. You are requesting a signed MDN - correct?
1. That signature verification fails - correct?

Possible parameters and reasons for this:
* You don't have the correct certificate configured in your partnership
* In certain configurations the certificate is contained in the MDN and the signature is verified against this certificate

To log the effective certificate that is used to verify the signature, the `AS2ClientSettings`  have a method `setVerificationCertificateConsumer` to provide a consumer that exactly receives this certificate and than you can log it. This method is available since v4.4.5

**Comment by Gentle-Chen** [comment] 2020-01-20 01:12
Hi @phax 

Plz see my answer below.
    

1. you are not using the latest version of as2-lib (v4.5.0) - correct?
Gentle: yes, i am using as2-lib v4.1.0, and due to it cannot support AES256 in v4.1.0, so I manually add the AES256 algorithm in the class `ECryptoAlgorithmCrypt`, also I changed some code for my business in the as2-lib.
2. you are sending an AS2 message - correct?
Gentle: yes
3. In that AS2 message your are requesting a sync MDN - correct?
Gentle: yes
4. You are requesting a signed MDN - correct?
Gentle: yes
5. That signature verification fails - correct?
Gentle: yes

So do you mean to it due to the wrong certificate in my side? 
And for the `setVerificationCertificateConsumer`, where should I use it, when I receiver the MDN?

**Comment by Gentle-Chen** [comment] 2020-01-20 07:41
Hi @phax 

I upgraded the as2-lib to the latest version and then retry, here is the error log.

Could you help to advise?

BTW
as2_mdn_options: `signed-receipt-protocol=optional, pkcs7-signature; signed-receipt-micalg=optional, SHA256`
sign_algorithm: `sha256`
encrypt_algorithm: `aes256-cbc`

[as2-log.txt](https://github.com/phax/as2-lib/files/4084961/as2-log.txt)

**Comment by phax** [comment] 2020-01-20 10:44
Hi @Gentle-Chen 

Okay, you have a "partnership" between you and your customer.
That partnership also contains the certificate of your partner.
It seems like this certificate differs from the certificate they are using when signing the MDN (based on `BCCryptoHelper  -  Verifying signature using the provided certificate (partnership)`).

Does that sound reasonable to you?

**Comment by Gentle-Chen** [comment] 2020-01-21 01:08
hi @phax 

Yes, I have partner's certificate on my side, I would get their certificate from my own keystore(the keystore already archived their certificate) and then verify.

So do you mean to it due to the different certificate between my side and theirs?

**Comment by Gentle-Chen** [comment] 2020-01-21 02:08
BTW, I also saw this log: 
```
"The message you sent on "[0x1f][0x1f][0xc2][0x8c], 21 [0x0][0x8] 2020 09:32:55 +0800" from "CARGOSMART" to[\r][\n]"
2020-01-21 09:32:56  [               DefaultMessageListenerContainer-1]  [DEBUG]                      Wire  -  http-outgoing-0 << ""KNTEST" with subject "CARGOSMART TEST 01" has been received on 21 Jan 2020[\r][\n]"
2020-01-21 09:32:56  [               DefaultMessageListenerContainer-1]  [DEBUG]                      Wire  -  http-outgoing-0 << "01:32:56 GMT, but cannot be processed because the following error occured:[\r][\n]"
2020-01-21 09:32:56  [               DefaultMessageListenerContainer-1]  [DEBUG]                      Wire  -  http-outgoing-0 << "[\r][\n]"
2020-01-21 09:32:56  [               DefaultMessageListenerContainer-1]  [DEBUG]                      Wire  -  http-outgoing-0 << " No matching decryption key found[\r][\n]"
2020-01-21 09:32:56  [               DefaultMessageListenerContainer-1]  [DEBUG]                      Wire  -  http-outgoing-0 << "[\r][\n]"
```

It shows no decryption key found, what it means to?

**Comment by phax** [comment] 2020-01-21 07:59
Symmetric encryption works so, that you are encrypting with the public key of the other side, and the other side decrypts with its private key.
In that case the other side sent you an encrypted MDN and it seems like the other side used a wrong certificate to encrypt the message? Does the other side eventually use an old certificate from you?

**Comment by Gentle-Chen** [comment] 2020-01-21 08:05
does the work flow like this?
I use my key to encrypt -> send msg to partner -> partner use my cert to decrypt -> partner use their key to encrypt -> send msg to me -> I use partner's cert to decrypt.

**Comment by phax** [comment] 2020-01-21 08:41
Close - you use your partners public key to encrypt, send it over, partner decrypts with his private key. Partner encrypts MDN with your public key, sends it over, you decrypt with your private key.

And with signing: you sign with your private key, send it, partner verifies with your public key. Partner creates MDN, signs it with his private key, sends it over, you verify with public key of Partner.

Hth

**Comment by Gentle-Chen** [comment] 2020-01-21 08:47
So according to your above words, do you mean to during signing, partner used the old cert from me to verify?

**Comment by phax** [comment] 2020-01-21 08:51
Yes there seems to be an inconsistency between the certificate they use for signing and the one you are using to verify....

**Comment by Gentle-Chen** [comment] 2020-01-21 08:53
And dose it like this?

I used partners public key to encrypt, and used my private key to sign, and then send, partner used my public key to verify, and then use his private key to decrypt. and then create MDN, sign with his private key and send to me, finally i verify with his public key?

**Comment by phax** [comment] 2020-01-21 09:01
Yes that's how it should be

**Comment by Gentle-Chen** [comment] 2020-01-21 09:03
ok, thanks for your help. @phax . I will check the cert between partner side and my side. I will close this issue.

Thanks a lot~

**Comment by phax** [comment] 2020-01-21 09:06
Close it when the issue is resolved. No need to hurry....

**Comment by Gentle-Chen** [comment] 2020-01-21 09:31
BTW, how should I use this method? 
Could you advise?

> `AS2ClientSettings `have a method `setVerificationCertificateConsumer`

**Comment by phax** [comment] 2020-01-21 09:49
You need to update to v4.5.0, than it is part of the AS2 Client Builder.
Just add a small consumer that logs the provided certificate to sysout or so. It should be the certificate used for signature verification

**Comment by phax** [comment] 2020-03-04 19:03
Closing this because of inactivity. If this is still an issue, please reopen

**Closed by phax** 2020-03-04 19:03 UTC
Labels: question
